# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/arcsolver',
                'doc_host': 'https://agemoai.github.io',
                'git_url': 'https://github.com/agemoai/arcsolver',
                'lib_path': 'arcsolver'},
  'syms': {'arcsolver.core': {'arcsolver.core.foo': ('core.html#foo', 'arcsolver/core.py')}}}
